blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions & questions
    url: https://github.com/m4c3/hass-hargassner-cloud/discussions
    about: Ask general questions or discuss usage with other users.
